sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t herekol1914/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true herekol1914/docker-react npm run test